### ISSUE TITLE
fix for width/height

### ISSUE THREAD

**Issue by wptmdoorn** [tercen/plot_fcs_shiny_operator#5]
Relevant code in workspace.R:

L56 - 57
```
sliderInput("plotWidth", "Plot width (px)", 200, 2000, 500),
sliderInput("plotHeight", "Plot height (px)", 200, 2000, 500),
```

L112 - 116
```
output$reacOut <- renderUI({
    plotOutput("main.plot",
               height = input$plotHeight,
               width = input$plotWidth)
})
```

It is of course essential that plotWidth and plotHeight are spelled EXACTLY the same on both places. 
This is currently not true for ui.R/server.R:

ui.R, L22-24
```
sliderInput("plot_width", "Plot width (px)", 200, 2000, 500),
sliderInput("plot_height", "Plot height (px)", 200, 2000, 500)
```

server.R, L275-L280
```
#output$biaxial <- renderUI({
#  plotOutput("theplot",
#             height = 500,
#             width = 750)
#})
```

Apart from that it should be commented out, we should use `input$plot_width` and `input$plot_height` (in workspace.R we used camelCase, but it's okay we use something different for ui.R/server.R). 
Should be changed to:

(new) server.R, L275-L280
```
output$biaxial <- renderUI({
  plotOutput("theplot",
             height = input$plot_height,
             width = input$plot_width)
})
```

**Comment by makostadima** [comment]
I don't use the workspace.R file for testing. The relevant lines are within the server.R script:

I currently set the dimensions of the plot manually in these [two lines](https://github.com/tercen/plot_fcs_shiny_operator/blob/66e23758bd26619be996bf28ce38ceb94a7690a5/server.R#L191).

The code that would allow me to change the plot's dimensions interactively is below starting from [this line](https://github.com/tercen/plot_fcs_shiny_operator/blob/66e23758bd26619be996bf28ce38ceb94a7690a5/server.R#L194). It is currently commented out because it is not working. I've tested it by setting the height and width within the plotOutput function to a fixed value first and the issue remains. I see no plot being drawn on the main page of the app.

The data I use to test can be found [here](https://tercen.com/MyrtoandWilliamshouse/w/abe673836a3f732410737d630179dffd/ds/d5c860cc-16e3-4834-bffb-4fca85548aa5).

**Comment by tsmonteiro** [comment]
Width and height are now reactive to changes in the input slider.
